### ISSUE TITLE
[TotalComputers] [STDERR] Fatal ERROR #1 -> Uncaught exception: Cannot invoke "com.jnngl.totalcomputers.TotalComputers$DoubleBuffer.get()" because the return value of "java.util.Map.get(Object)" is null

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#1]
Occured when computer is used by one of my players.
???

**Comment by JNNGL** [comment]
[Download](https://github.com/JNNGL/TotalComputers/suites/6539657143/artifacts/244044471) latest version from Actions workflow and see if it fixes the bug

**Comment by Erisfiregamer1** [comment]
Worthless because server is ARM64, is fixed tho so closing.
(please add arm64 support)

**Comment by JNNGL** [comment]
You can [compile plugin](https://github.com/JNNGL/TotalComputers/wiki/Building-the-plugin-%7C-%D0%A1%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0) yourself or use [build without natives](https://github.com/JNNGL/TotalComputers/raw/appbase/TotalComputers-0.9b-no_natives.jar) (but it is outdated). Anyway, browser, video player and virtualbox won't work on arm

**Comment by Erisfiregamer1** [comment]
How would you be able to fix that? I'd love to have this plugin on my server with full support.
