### ISSUE TITLE
[Feature request] Load AARCH64 (arm64) natives when detected

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#10]
I've got these natives available for use (directly built from an ARM64 machine), and these could be added to support ARM a little better.
This would also fix the consistent "could not load natives" error when computers are turned on / created when using an ARM64 machine.
Not sure how you're going to check in Java though, otherwise I'd do it.

**Comment by JNNGL** [comment]
[no natives](https://github.com/JNNGL/TotalComputers/commit/66d55658d362f269eb637d8d637bc79aea8cc678), no problems =)

**Comment by Erisfiregamer1** [comment]
RIP natives :(
