### ISSUE TITLE
[Feature Request] Full ARM64 support

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#2]
The Oracle Cloud offers a really good VM that could be used to run Minecraft, but it's ARM64, and this plugin has ~~no~~ miminal support for it.
Offering full support would make this plugin way more popular, as a lot more people could use it.

**Comment by afkvido** [comment]
sup eris

**Comment by Erisfiregamer1** [comment]
oh hi vido

**Comment by afkvido** [comment]
it's **oracle cloud** again 
## :)

**Comment by walksanatora** [comment]
was just with him on discord
we were able to get it to compile arm
will be working towards more applications working (although i think they allready work)

**Comment by afkvido** [comment]
cool

**Comment by JNNGL** [comment]
natives are unnecessary for linux at the moment

**Comment by afkvido** [comment]
Y tho? Linux support is important

**Comment by JNNGL** [comment]
this doesnt affect functionality on linux (at the moment)
but browser, video player and vbox won't work on arm anyway

**Comment by JNNGL** [comment]
anyway virtual box doesnt support arm at all

**Comment by afkvido** [comment]
_"Easy"_

sureeeeee

**Comment by walksanatora** [comment]
conditional compile directives exist for a reason
also i was considering making it so instead of webrdp we have a dedicated RDP app that you can then use with virtual box

**Comment by JNNGL** [comment]
actually vbox app already uses rmi.
i can add a 'connect' button that will connect to existing rmi server instead of creating one

**Comment by Erisfiregamer1** [comment]
So you could recompile the 2 other apps for ARM64 and add the "Connect" button for VBox? Sounds good to me.

**Comment by JNNGL** [comment]
But then it will transfer 40-700 MB per second

**Comment by Erisfiregamer1** [comment]
We could add a command to enable it for admins, warning them "This takes a
LOT of bandwidth".

**Comment by JNNGL** [comment]
Also you will need to make port 2099 available from the outside

**Comment by afkvido** [comment]
**This takes 40-700 MB of bandwidth per second.**

**Comment by JNNGL** [comment]
Or 2.7 GB per second if OS supports 8k

**Comment by Erisfiregamer1** [comment]
> Also you will need to make port 2099 available from the outside

I could easily do that, and I bet most other server owners could as well.

**Comment by Erisfiregamer1** [comment]
> **This takes 40-700 MB of bandwidth per second.**

Sounds good to me.

**Comment by Erisfiregamer1** [comment]
I took a hot minute to compile the binaries for ARM64. Here you go.
[Archive.zip](https://github.com/JNNGL/TotalComputers/files/8778870/Archive.zip)

**Comment by Erisfiregamer1** [comment]
Well the natives are fucking dead now. We'll just gotta focus on recompiling the amd64 apps.

**Comment by JNNGL** [comment]
and the video player will weigh 800 MB

**Comment by JNNGL** [comment]
the browser will weigh >3 GB

**Comment by Erisfiregamer1** [comment]
That
is a problem.

**Comment by JNNGL** [comment]
maybe just add connect button that will connect to an existing rmi server?

**Comment by Erisfiregamer1** [comment]
... That works too.

**Comment by JNNGL** [comment]
this can now be fixed with clientbound pcs

**Comment by Erisfiregamer1** [comment]
Going to close; clientbound PCs are a thing now, niice.
