### ISSUE TITLE
BSOD throws error on usage

### ISSUE THREAD

**Issue by Erisfiregamer1** [JNNGL/TotalComputers#8]
[18:18:15 ERROR]: [TotalComputers] [STDERR] Critical Error -> Uncaught exception: Index 0 out of bounds for length 0
Error should be silenced as to not freak out developers.

**Comment by JNNGL** [comment]
That's how it should be. BSoD appears if the OS or some application throws exceptions for 3 seconds without stopping. So the BSoD application throws exceptions every tick to check if the blue screen of death will appear if the operating system freezes

**Comment by Erisfiregamer1** [comment]
Ah. Just freaked me out seeing an error in the console, because **3 times now** my userbase has crashed my server via this plugin.
